# Generated by Django 4.2.4 on 2023-09-19 19:28

import ckeditor.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_nation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gallary', models.BooleanField(default=False)),
                ('simple_discription', models.CharField(max_length=40)),
                ('district', models.CharField(choices=[('Balaka', 'Balaka'), ('Blantyre', 'Blantyre'), ('Chikwawa', 'Chikwawa'), ('Chiradzuru', 'Chiradzuru'), ('Chitipa', 'Chitipa'), ('Dedza', 'Dedza'), ('Dowa', 'Dowa'), ('Karonga', 'Karonga'), ('Kasungu', 'Kasungu'), ('Likoma', 'Likoma'), ('Lilongwe', 'Lilongwe'), ('Machinga', 'Machinga'), ('Mangochi', 'Mangochi'), ('Mchinji', 'Mchinji'), ('Mulanje', 'Mulanje'), ('Mwanza', 'Mwanza'), ('Mzimba', 'Mzimba'), ('Neno', 'Neno'), ('Nkhata_Bay', 'Nkhata_Bay'), ('Nkhotakota', 'Nkhotakota'), ('Nsanje', 'Nsanje'), ('Ntcheu', 'Ntcheu'), ('Ntchisi', 'Ntchisi'), ('Phalombe', 'Phalombe'), ('Ruphi', 'Ruphi'), ('Salima', 'Salima'), ('Thyolo', 'Thyolo'), ('Zomba', 'Zomba'), ('Others', 'Others')], default='Mwanza', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('youtube_video_link', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('weblink', models.URLField(blank=True, null=True)),
                ('product_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('product_image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('product_image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('product_image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('payment_method', models.CharField(choices=[('TNM', 'Mpamba'), ('Airtel', 'Aitel Money'), ('NB', 'National Bank')], max_length=20, null=True)),
                ('refu', models.CharField(max_length=20, null=True)),
                ('acc_Name', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_nation.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.product')),
            ],
        ),
    ]
