# Generated by Django 4.2.4 on 2023-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='Store/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='Store/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='Store/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='Store/%y/%m/%d'),
        ),
    ]
