# Generated by Django 4.2.4 on 2023-09-19 19:28

import ckeditor.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BooleanField(default=False)),
                ('ticketCategory', models.CharField(choices=[('Conferences', 'Conferences'), ('Music shows', 'Music shows'), ('Sports', 'Sports'), ('Trade shows', 'Trade shows'), ('Seminars', 'Seminars'), ('Company meetings and off-sites', 'Company meetings and off-sites'), ('Team building', 'Team building'), ('Product or service launch', 'Product or service launch'), ('Weddings', 'Weddings'), ('Festivals', 'Festivals'), ('Exhibitions', 'Exhibitions'), ('Charity events', 'Charity events'), ('Fashion shows and red carpets', 'Fashion shows and red carpets')], default='Music shows', max_length=100)),
                ('name', models.CharField(max_length=40)),
                ('simple_discription', models.CharField(max_length=40)),
                ('number_of_tickets', models.PositiveIntegerField(default=0)),
                ('ticket_booked', models.PositiveIntegerField(default=0)),
                ('district', models.CharField(choices=[('Balaka', 'Balaka'), ('Blantyre', 'Blantyre'), ('Chikwawa', 'Chikwawa'), ('Chiradzuru', 'Chiradzuru'), ('Chitipa', 'Chitipa'), ('Dedza', 'Dedza'), ('Dowa', 'Dowa'), ('Karonga', 'Karonga'), ('Kasungu', 'Kasungu'), ('Likoma', 'Likoma'), ('Lilongwe', 'Lilongwe'), ('Machinga', 'Machinga'), ('Mangochi', 'Mangochi'), ('Mchinji', 'Mchinji'), ('Mulanje', 'Mulanje'), ('Mwanza', 'Mwanza'), ('Mzimba', 'Mzimba'), ('Neno', 'Neno'), ('Nkhata_Bay', 'Nkhata_Bay'), ('Nkhotakota', 'Nkhotakota'), ('Nsanje', 'Nsanje'), ('Ntcheu', 'Ntcheu'), ('Ntchisi', 'Ntchisi'), ('Phalombe', 'Phalombe'), ('Ruphi', 'Ruphi'), ('Salima', 'Salima'), ('Thyolo', 'Thyolo'), ('Zomba', 'Zomba'), ('Others', 'Others')], default='Mwanza', max_length=40)),
                ('venue', models.CharField(blank=True, max_length=40, null=True)),
                ('from_t', models.TimeField(blank=True, null=True)),
                ('from_d', models.DateField(blank=True, max_length=40, null=True)),
                ('to_t', models.TimeField(blank=True, null=True)),
                ('to_d', models.DateField(blank=True, max_length=40, null=True)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('vip_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('youtube_video_link', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('product_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('ticketObjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ticketsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tickets_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(choices=[('Approved', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=40)),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mathod', models.CharField(blank=True, max_length=100, null=True)),
                ('account_num', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Event.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
