# Generated by Django 4.2.4 on 2023-09-19 19:28

import ckeditor.fields
import cloudinary.models
import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('album_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='artwork')),
                ('album_genre', models.CharField(choices=[('House', 'House'), ('Hip Hop', 'Hip hop'), ('Trap', 'Trap'), ('Raggie', 'Raggie'), ('Amapiano', 'Amapiano'), ('Gospel', 'Gospel'), ('Beats', 'Beats'), ('Afro pop', 'Afro pop'), ('Afro House', 'Afro House'), ('Dancehall', 'Dancehall'), ('Poetry', 'Poetry/Poem'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Indie', 'Indie'), ('Jazz', 'Jazz'), ('Latino', 'Latino'), ('R&B', 'R&B')], max_length=30)),
                ('aboutAlbum', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('songsNum', models.PositiveIntegerField(default=0)),
                ('streamNum', models.PositiveIntegerField(default=0)),
                ('sell', models.CharField(choices=[('Free', 'Free'), ('Sale', 'Sale')], max_length=100)),
                ('most_sold', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=40)),
                ('Artist', models.CharField(blank=True, max_length=40, null=True)),
                ('song_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='song')),
                ('song_genre', models.CharField(choices=[('House', 'House'), ('Hip Hop', 'Hip hop'), ('Trap', 'Trap'), ('Raggie', 'Raggie'), ('Amapiano', 'Amapiano'), ('Gospel', 'Gospel'), ('Beats', 'Beats'), ('Afro pop', 'Afro pop'), ('Afro House', 'Afro House'), ('Dancehall', 'Dancehall'), ('Poetry', 'Poetry/Poem'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Indie', 'Indie'), ('Jazz', 'Jazz'), ('Latino', 'Latino'), ('R&B', 'R&B')], max_length=30)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('streamingCount', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=0)),
                ('sell', models.CharField(choices=[('Free', 'Free'), ('Sale', 'Sale')], max_length=100)),
                ('most_sold', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_nation.album')),
            ],
        ),
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Arts', 'Arts'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Fiction', 'Fiction'), ('Government', 'Government'), ('History', 'History'), ('Health & Fitness', 'Health & Fitness'), ('Kids & Family', 'Kids & Family'), ('Leisure', 'Leisure'), ('News', 'News'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Science', 'Science'), ('Society & Culture', 'Society & Culture'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('True Crime', 'True Crime'), ('TV & Film', 'TV & Film')], default='Music', max_length=40)),
                ('youtubelink', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Artist', 'Artist')], max_length=40)),
                ('profile_pic', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('artist_genre', models.CharField(choices=[('House', 'House'), ('Hip Hop', 'Hip hop'), ('Trap', 'Trap'), ('Raggie', 'Raggie'), ('Amapiano', 'Amapiano'), ('Gospel', 'Gospel'), ('Beats', 'Beats'), ('Afro pop', 'Afro pop'), ('Afro House', 'Afro House'), ('Dancehall', 'Dancehall'), ('Poetry', 'Poetry/Poem'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Indie', 'Indie'), ('Jazz', 'Jazz'), ('Latino', 'Latino'), ('R&B', 'R&B')], max_length=30)),
                ('fb', models.URLField(blank=True, null=True)),
                ('tweeter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('background', models.CharField(blank=True, max_length=200, null=True)),
                ('fullBiography', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='music_nation.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
