# Generated by Django 4.2.4 on 2023-09-21 10:45

from django.db import migrations, models
import music_nation.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to=music_nation.models.upload_audio_location),
        ),
    ]
