# Generated by Django 4.2.4 on 2023-09-21 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0002_song_artwork_alter_album_album_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, null=True, unique=True),
        ),
    ]
