# Generated by Django 4.2.4 on 2023-09-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0003_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
