# Generated by Django 4.2.4 on 2023-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0006_album_aproved_song_aproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, default='www/img/ikartwork.jpg', null=True, upload_to='artwork/%y/%m/%d'),
        ),
    ]
