# Generated by Django 4.2.4 on 2023-09-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0007_alter_song_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/%y/%m/%d'),
        ),
    ]
