# Generated by Django 4.2.4 on 2023-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0008_alter_song_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default='ikartwork.jpg', null=True, upload_to='artwork/%y/%m/%d'),
        ),
    ]
