# Generated by Django 4.2.4 on 2023-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0009_alter_album_album_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='ikartwork.jpg', null=True, upload_to='profile/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, default='ikartwork.jpg', null=True, upload_to='artwork/%y/%m/%d'),
        ),
    ]
