# Generated by Django 4.2.4 on 2023-09-19 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PymtCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mid', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicorEventPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('TNM', 'TNM Mpamba'), ('Airtel', 'Aitel Money'), ('NB', 'National Bank')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('category', models.CharField(choices=[('Event', 'Event Tickets'), ('Music', 'Music Upload')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('PaymentReferenceNumber', models.CharField(max_length=100)),
                ('aprove', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
