# Generated by Django 4.2.4 on 2023-09-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikpixels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicoreventpayment',
            name='name',
            field=models.CharField(default='isaac', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicoreventpayment',
            name='phone',
            field=models.CharField(default='4343', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicoreventpayment',
            name='payment_method',
            field=models.CharField(choices=[('TNM', 'TNM Mpamba'), ('Airtel', 'Airtel Money'), ('NB', 'National Bank')], max_length=40),
        ),
    ]
