# Generated by Django 4.2.4 on 2023-09-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikpixels', '0004_musicoreventpayment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicoreventpayment',
            name='item_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicoreventpayment',
            name='category',
            field=models.CharField(choices=[('Event', 'Event-Tickets Marketing'), ('Music', 'Music Upload'), ('Music_Purchase', 'Buying Music')], max_length=40),
        ),
    ]
